name: Release Docker

env:
  DOCKER_HUB_LOGIN: anthonyjhoiro
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  PREFIX: pref

on: 
  release:
    types: [published]

jobs:  
  docker-release:
    name: Docker deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ['module1', 'module2']
    
    steps:
      - name: Get image name
        run: echo "::set-output name=image_name::$DOCKER_HUB_LOGIN/$PREFIX_$(basename ${{ matrix.module }})"
        id: image_name
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: anthonyjhoiro
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ matrix.module }}
          tags: |
            ${{ steps.image_name.outputs.image_name }}:latest
            ${{ steps.image_name.outputs.image_name }}:${GITHUB_REF##*/}